KTB-04
smokewolfy/LearnEngWordsBot pull request #2
Opened 2024-06-24 05:57 UTC by smokewolfy

2024-06-26 08:45 UTC, danelyan requested changes

2024-06-26 08:45 UTC, danelyan commented on src/main/kotlin/additional/files.kt
> +    val eng: String,
Давай сделаем класс чуть универсальнее.
Поле `eng` переименуем в `original`, а поле `rus` → `translate`.

Тогда мы сможем переиспользовать этот класс и для создание бота, например, для изучения немецких слов. К тому же само название класса не отсылает к русскому языку. Если бы класс был, к примеру, RussianWord() и имел специфичные для русского языка особенности, то да.

2024-06-26 08:45 UTC, danelyan commented on src/main/kotlin/additional/files.kt
> +        dictionary.add(Word(eng = line[0], rus = line[1], correctAnswerCount = line[2].toIntOrNull() ?: 0))
попробуй в словарь добавить строку:
```txt
good|хороший
```

Нужно проверять размер списка line

2024-07-10 19:11 UTC, smokewolfy commented on src/main/kotlin/additional/files.kt
> +        dictionary.add(Word(eng = line[0], rus = line[1], correctAnswerCount = line[2].toIntOrNull() ?: 0))
добавить только проверку на наличие числа правильных ответов, или запилить полную проверку всей строки(слово-перевод-count)?

2024-07-16 08:44 UTC, danelyan requested changes

2024-07-16 08:44 UTC, danelyan commented on src/main/kotlin/additional/files.kt
> +        dictionary.add(Word(eng = line[0], rus = line[1], correctAnswerCount = line[2].toIntOrNull() ?: 0))
Достаточно только проверить размер

2024-07-16 09:37 UTC, danelyan approved these changes

2024-07-16 10:50 UTC, closed without merging