KTB-05
smokewolfy/LearnEngWordsBot pull request #3
Opened 2024-07-16 10:53 UTC by smokewolfy

2024-07-16 13:37 UTC, danelyan requested changes

2024-07-16 13:37 UTC, danelyan commented on src/main/kotlin/additional/files.kt
> +    file.readLines().forEach {
давай уже вынесем в метод loadDictionary код для загрузки словаря

2024-07-16 13:37 UTC, danelyan commented on src/main/kotlin/additional/files.kt
> +        when (readln().toInt()) {
тут лучше toIntOrNull() тогда, чтобы добавить else, тем самым обработав некорректный ввод

2024-07-16 13:39 UTC, smokewolfy commented on src/main/kotlin/additional/files.kt
> +    file.readLines().forEach {
ща накатаю.

2024-07-16 13:41 UTC, smokewolfy commented on src/main/kotlin/additional/files.kt
> +        when (readln().toInt()) {
действительно

2024-07-16 15:35 UTC, danelyan approved these changes

2024-07-18 06:19 UTC, danelyan approved these changes

2025-04-05 10:22 UTC, merged