KTB-06
smokewolfy/LearnEngWordsBot pull request #4
Opened 2024-07-18 06:29 UTC by smokewolfy

2024-07-20 15:31 UTC, danelyan requested changes

2024-07-20 15:31 UTC, danelyan commented on src/main/kotlin/additional/files.kt
> +fun statistics(dictionary: MutableList<Word>): String {
методы мы называем глаголами. Например calculateStatistics() или getStatistics(). Иногда позволительно использовать существительные в названиях функций, но это как правило при разработки всяких [DSL](https://habr.com/ru/articles/343730/)

2024-07-20 15:31 UTC, danelyan commented on src/main/kotlin/additional/files.kt
> +    val progressPercentage = learnedWordsCount * 100 / 7
Почему 7?
Нам нужно поделить на общее количество слов в словаре. Это количество может поменяться. Тебе просто нужен dictionary.size вместо 7

2024-07-20 15:31 UTC, danelyan commented on src/main/kotlin/additional/files.kt
> +fun statistics(dictionary: MutableList<Word>): String {
И еще, нам не нужен MutableList, достаточно просто List. Старайся использовать минимально необходимый интерфейс в методах/переменных. Так ты снижаешь связанность кода. К примеру, список можно будет подменить каким-то другим, неизменяемым в данном случае.

2024-07-20 19:10 UTC, smokewolfy commented on src/main/kotlin/additional/files.kt
> +    val progressPercentage = learnedWordsCount * 100 / 7
честно говоря, не знаю что было у меня в голове в этот момент. аллергия обострилась и голова не соображала

2024-07-23 08:15 UTC, danelyan approved these changes

2025-04-05 10:22 UTC, merged